### PR TITLE
Add load-mock-data command

### PR DESCRIPTION
**Pull request by mzbroch**
Adds nautobot demo data - size small
Changes secret keys

Tested:
- [x] Import
- [x] Migrations
- [x] Works successfully on 1.6, current NAUTOBOT_VER

### CODE REVIEW

**Comment by jtdub** [comment]
The problem that was created by this in the past was that as models changed or if you wanted to add plugins, that loading data from a dump would fail because the SQL file wouldn't take into account model changes from core or from plugins. A better solution would to create a mock data set from the ORM rather than loading SQL data from a dump.

This potentially also undoes custom default accounts that a user may create when they spin up their container: https://github.com/nautobot/nautobot-lab/blob/main/templates/default_user.py

I will also point you to the recent blog for further explanation. https://blog.networktocode.com/post/whats-new-with-nautobot-lab/

**Comment by mzbroch** [comment]
> The problem that was created by this in the past was that as models changed or if you wanted to add plugins, that loading data from a dump would fail because the SQL file wouldn't take into account model changes from core or from plugins. A better solution would to create a mock data set from the ORM rather than loading SQL data from a dump.

This is no longer a problem - here we provide a centralised, standard dataset that is updated between releases and plugins. Same as public demo instance.

**Comment by jtdub** [comment]
Please add a section to the readme about the mock data, what it gives you and a note about it overwriting a custom default user.

**Comment by mzbroch** [comment]
> Please add a section to the readme about the mock data, what it gives you and a note about it overwriting a custom default user.

Done

**Review by jtdub — APPROVED** [review]
LGTM!

**Pull request merged**
